### ISSUE TITLE
📖 [Docs]: Design/Rework README.md

### ISSUE THREAD

**Issue by N3v1** [ScribbleLabApp/ScribbleLab#45]
### Description

Greetings everyone!
We hope this message finds you in good health and high spirits. 

As you all know, we have been working on the repository for quite some time now, and while it has served us well, we believe that it's time for a revamp. 

We are looking for individuals who are skilled in restyling and have an eye for detail to help us redesign the repository’s README. Our aim is to make it look sleek, informative, and lightweight. 

If you're interested in working with us on this project, please let us know by leaving a comment below. Your assistance will be greatly appreciated! 

Thank you for your time and consideration.

## To Do's
- [ ] Add translations of README (German, Korean, Italian, Spanish, `other languages on request`)
- [x] Redesign README
- [x] Restructure README
- [x] Adding nice graphics and photos related to our app
- [ ] Working on the documentation

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by minaelee** [comment]
I am interested.

**Comment by N3v1** [comment]
> I am interested.

I appreciate your interest in this contribution 🙏

> [!Note]
> I have created a second repository called `docs` on this organization. To maintain a better overview of this huge project, I think keeping only the README.md and other essential files on the main repository would be better. Meanwhile, the translation of the README and other documents, such as API documentation, should be kept on the `docs` repository.

Explore our `documentation` repo [here](https://github.com/ScribbleLabApp/docs)

**Comment by N3v1** [comment]
@minaelee If you need any help regarding this big "issue", just let me know 🙂

Best regards
NH 
--
Founder of ScribbleLab
