### ISSUE TITLE
[i18n]: Translate README.md

### ISSUE THREAD

**Issue by N3v1** [ScribbleLabApp/ScribbleLab#55]
### Description

Hey everyone,
we need help to translate README.md into multiple languages. Please find the list of languages that need to be supported below:

| Language | Assignee |  Status |
|-----------|----------|---------|
| Italian        |  @N3v1 & @ctrlVnt   | Done       |
| German    | @N3v1    |  WIP      |
| Spanish    | @kamdvc  |    Done        |
| Polish        |       -        |   -         |
| Dutch       | @kilian-balaguer |  WIP |
| Japanese |       -         |   -         |
| Chinese   |       -          |    -         |
| Korean     |      -           |    -         | 

If you want a not listed language just ask 👍

### Version

> none

### To Reproduce

> none

### Additional Context

In the "documentation" folder of this repository, create a new file named README~[your language].md for translation.

e.g. German translation -> README~de.md

Once you've finished translating the README, you can include your language in the main README (en).

### Screenshots

> none

### Is there an existing translation issue for this?

- [X] I have searched the existing issues

**Comment by kamdvc** [comment]
Hello! I would like to contribute to your repo, would you mind if I add the Spanish language?

**Comment by N3v1** [comment]
> Hello! I would like to contribute to your repo, would you mind if I add the Spanish language?

Sure you can 👍🏼 
Thank you in advance for your contribution

**Comment by ctrlVnt** [comment]
Hi !
If you want I can do the Italian translation !

**Comment by N3v1** [comment]
> Hi ! If you want I can do the Italian translation !

Sure 👍🏼 Thank you in advance for your contribution

**Comment by N3v1** [comment]
Hey @kamdvc,
how is your Spanish translation going? Do you need any help?
